/*
 * Raima Database Compiled Catalog Header File
 * This file is autogenerated, please don't edit the file
*/

#if !defined(CARDSDB_CAT_H)
#define CARDSDB_CAT_H
/*lint ++flb */

#include "rdm.h"

#if defined(__cplusplus)
extern "C"
{
#endif

RDM_EXTERN const char * const cardsdb_cat; /*lint !e956 */

#if defined(__cplusplus)
}
#endif


/*lint --flb */
#endif /* CARDSDB_CAT_H */
