/*
 * Raima file 
 *
 * Copyright (c) 2016 by Raima Inc.
 * All rights reserved.
 *
 * This file is autogenerated, please don't edit the file.
 */

#if !defined(CARDSDB_EMBED_H)
#define CARDSDB_EMBED_H

#include "rdm.h"
#include "embedfileapi.h"
#include "cardsdb_cat.h"

#if defined(__cplusplus)
extern "C" {
#endif

RDM_RETCODE embed_cardsdb_cat (const char *, B_EMBED_COMMAND, const char *, RDM_TFS, const char *);

#if defined(__cplusplus)
}
#endif

#endif
