/*
 * Raima Database Header File
 * This file is autogenerated, please don't edit the file
*/

#if !defined(CARDSDB_H)
#define CARDSDB_H

#include "rdm.h"
/*lint ++flb */

/* table structure definitions */
typedef struct CARD_INFO_S
{
    uint64_t access_rules_record_addr;
    uint8_t card_access_type;
    uint8_t token_digest[35];
    char last_digits[5];
} CARD_INFO;

typedef struct CARD_ACCESS_RULES_S
{
    uint8_t access_data[500];
} CARD_ACCESS_RULES;

/* compound key structure definitions */
typedef struct CARD_INFO_TOKEN_DIGEST_KEY_S
{
    uint8_t token_digest[35];
} CARD_INFO_TOKEN_DIGEST_KEY;

/* table identifiers enum */
typedef enum CARDSDB_TABLES_E
{
    TABLE_CARD_INFO = 0x10000,
    TABLE_CARD_ACCESS_RULES = 0x10001
} CARDSDB_TABLES;

/* column identifiers enum */
typedef enum CARDSDB_COLUMNS_E
{
    COL_CARD_INFO_ACCESS_RULES_RECORD_ADDR = 0x00000000,
    COL_CARD_INFO_CARD_ACCESS_TYPE = 0x00000001,
    COL_CARD_INFO_TOKEN_DIGEST = 0x00000002,
    COL_CARD_INFO_LAST_DIGITS = 0x00000003,
    COL_CARD_ACCESS_RULES_ACCESS_DATA = 0x00020000
} CARDSDB_COLUMNS;

/* key identifiers enum */
typedef enum CARDSDB_KEYS_E
{
    KEY_CARD_INFO_TOKEN_DIGEST = 0x8000
} CARDSDB_KEYS;

/*lint --flb -esym(641,CARDSDB_TABLES_E,CARDSDB_COLUMNS_E,CARDSDB_KEYS_E,CARDSDB_REFS_E) */
#endif /* CARDSDB_H */
